# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Dell/Desktop/CICC/High_speed_multi_port_shared_cache_management_module/bulid/Top.srcs/sources_1/ip/data_fifo/data_fifo.xci
# IP: The module: 'data_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Dell/Desktop/CICC/High_speed_multi_port_shared_cache_management_module/bulid/Top.srcs/sources_1/ip/data_fifo/data_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Dell/Desktop/CICC/High_speed_multi_port_shared_cache_management_module/bulid/Top.srcs/sources_1/ip/data_fifo/data_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Dell/Desktop/CICC/High_speed_multi_port_shared_cache_management_module/bulid/Top.srcs/sources_1/ip/data_fifo/data_fifo.xci
# IP: The module: 'data_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Dell/Desktop/CICC/High_speed_multi_port_shared_cache_management_module/bulid/Top.srcs/sources_1/ip/data_fifo/data_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Dell/Desktop/CICC/High_speed_multi_port_shared_cache_management_module/bulid/Top.srcs/sources_1/ip/data_fifo/data_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
