# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Dell/Desktop/CICC/High_speed_multi_port_shared_cache_management_module/ip/wr_fifo/wr_fifo.xci
# IP: The module: 'wr_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Dell/Desktop/CICC/High_speed_multi_port_shared_cache_management_module/ip/wr_fifo/wr_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'wr_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Dell/Desktop/CICC/High_speed_multi_port_shared_cache_management_module/ip/wr_fifo/wr_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'wr_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Dell/Desktop/CICC/High_speed_multi_port_shared_cache_management_module/ip/wr_fifo/wr_fifo.xci
# IP: The module: 'wr_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Dell/Desktop/CICC/High_speed_multi_port_shared_cache_management_module/ip/wr_fifo/wr_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'wr_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Dell/Desktop/CICC/High_speed_multi_port_shared_cache_management_module/ip/wr_fifo/wr_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'wr_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
