# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.modelsimInstallPath E:/FPGA/modelsim/win64
set_msg_config  -id {Project 1-311}  -string {{CRITICAL WARNING: [Project 1-311] Could not find the file 'C:/Users/Dell/Desktop/CICC/plan0427/Src/rd_sram.v', nor could it be found using path 'F:/A/2024/plan0427/Src/rd_sram.v'.}}  -suppress 
create_project -in_memory -part xc7a50tlftg256-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Dell/Desktop/CICC/plan0427/Bulid/Top.cache/wt [current_project]
set_property parent.project_path C:/Users/Dell/Desktop/CICC/plan0427/Bulid/Top.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Dell/Desktop/CICC/plan0427/Bulid/Top.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Dell/Desktop/CICC/plan0427/Src/addr_ctrl.v
  C:/Users/Dell/Desktop/CICC/plan0427/Src/addr_gen.v
  C:/Users/Dell/Desktop/CICC/plan0427/Src/addr_re.v
  C:/Users/Dell/Desktop/CICC/plan0427/Src/check.v
  C:/Users/Dell/Desktop/CICC/plan0427/Src/queue_gen.v
  C:/Users/Dell/Desktop/CICC/plan0427/Src/wr_lead.v
  C:/Users/Dell/Desktop/CICC/plan0427/Src/wr_sram.v
  C:/Users/Dell/Desktop/CICC/plan0427/Src/Top.v
}
read_ip -quiet C:/Users/Dell/Desktop/CICC/plan0427/Ip/wr_fifo/wr_fifo.xci
set_property used_in_implementation false [get_files -all c:/Users/Dell/Desktop/CICC/plan0427/Ip/wr_fifo/wr_fifo.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dell/Desktop/CICC/plan0427/Ip/wr_fifo/wr_fifo_ooc.xdc]

read_ip -quiet C:/Users/Dell/Desktop/CICC/plan0427/Ip/data_fifo/data_fifo.xci
set_property used_in_implementation false [get_files -all c:/Users/Dell/Desktop/CICC/plan0427/Ip/data_fifo/data_fifo.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dell/Desktop/CICC/plan0427/Ip/data_fifo/data_fifo_ooc.xdc]

read_ip -quiet C:/Users/Dell/Desktop/CICC/plan0427/Ip/queue_fifo/queue_fifo.xci
set_property used_in_implementation false [get_files -all c:/Users/Dell/Desktop/CICC/plan0427/Ip/queue_fifo/queue_fifo.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dell/Desktop/CICC/plan0427/Ip/queue_fifo/queue_fifo_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Top -part xc7a50tlftg256-2L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
